### ISSUE TITLE
请问skypile-150B数据集怎么消失了？

### ISSUE THREAD

**Issue by haochange** [padeoe/hf-mirror-site#1]

**Comment by padeoe** [comment]
看了下是huggingface上官方也下架了，原因不清楚

**Comment by padeoe** [comment]
如有需要可私信联系可私下传一份给你，我先关闭issue了

**Comment by YIZXIY** [comment]
@padeoe 我也在寻找skypile-150B但是在hf-mirror.com的torrent失效了下载不下来，可以更新一下或者发到下面这个邮箱里吗  zx@zxgov.org

**Comment by padeoe** [comment]
> @padeoe 我也在寻找skypile-150B但是在hf-mirror.com的torrent失效了下载不下来，可以更新一下或者发到下面这个邮箱里吗  zx@zxgov.org

可以下载的，请用请使用以下客户端：uTorrent、qBittorrent、Transmission，不支持迅雷等其他客户端

**Comment by KinglyWayne** [comment]
@padeoe 麻烦能分享一下torrent吗？ 邮箱：kinglywayne#gmail.com  感谢:-)

**Comment by padeoe** [comment]
> @padeoe 麻烦能分享一下torrent吗？ 邮箱：kinglywayne#gmail.com 感谢:-)

在 hf-mirror.com 首页输入关键词搜索即可

**Comment by KinglyWayne** [comment]
> > @padeoe 麻烦能分享一下torrent吗？ 邮箱：kinglywayne#gmail.com 感谢:-)
> 
> 在 hf-mirror.com 首页输入关键词搜索即可

搜索skypile-150B之后跳转到镜像站，而镜像站里面该数据集已经下线了

**Comment by padeoe** [comment]
> > > @padeoe 麻烦能分享一下torrent吗？ 邮箱：kinglywayne#gmail.com 感谢:-)
> > 
> > 
> > 在 hf-mirror.com 首页输入关键词搜索即可
> 
> 搜索skypile-150B之后跳转到镜像站，而镜像站里面该数据集已经下线了

搜索框输入sky，不要按enter，等待两秒就能看到
