### ISSUE TITLE
hfd下载脚本无法处理带空格的文件名

### ISSUE THREAD

**Issue by MingfuYAN** [padeoe/hf-mirror-site#24]
非常感谢您出色的工作，我发现了hfd下载脚本一个bug，如果文件名中有空格，下载路径就会被截断，如，`https://huggingface.co/Tencent-Hunyuan/HunyuanDiT/tree/main/asset/chinese elements understanding.png`
，但是最后识别成这个 `https://huggingface.co/Tencent-Hunyuan/HunyuanDiT/tree/main/asset/chinese`

下载命令：`./hfd.sh Tencent-Hunyuan/HunyuanDiT --tool wget`

**Comment by padeoe** [comment]
[Fixed](https://gist.github.com/padeoe/697678ab8e528b85a2a7bddafea1fa4f/revisions#diff-c2fa4332abc741371ff2407a592e8a32141f0576321a85f23572b23801053a35R118). Thank you for your feedback!
