### ISSUE TITLE
请支持civitai

### ISSUE THREAD

**Issue by hipudding** [padeoe/hf-mirror-site#3]
感谢老哥提供的hf镜像站，解决了很大的问题。
请问能把civitai也做个镜像站么？多谢

**Comment by padeoe** [comment]
这个有点难呢，看了下上面内容不合规的挺多的，难顶😂

**Comment by hipudding** [comment]
额。好的，多谢。这东西真废流量啊主要是

**Comment by padeoe** [comment]
> 额。好的，多谢。这东西真废流量啊主要是

是真的费流量，日均15TB流量；日均一百万request。

**Comment by hipudding** [comment]
好人一生平安

**Comment by chenyaofo** [comment]
> > 额。好的，多谢。这东西真废流量啊主要是
> 
> 是真的费流量，日均15TB流量；日均一百万request。

不算波峰波谷，15TB就是182MB/s，这都奔着2G的带宽去了，听着就很贵
