### ISSUE TITLE
docker caddy2.7 镜像启动无法识别 replace 指令

### ISSUE THREAD

**Issue by lly-ke** [padeoe/hf-mirror-site#5]
<img width="838" alt="image" src="https://github.com/padeoe/hf-mirror-site/assets/28623614/0a469986-e4d6-4c2e-a20b-6de8d0646649">

我用caddy2.7镜像启动, hf-mirror.com.Caddyfile 文件中 109 行 replace 指令识别不了

**Comment by lly-ke** [comment]
另外一个问题: 浏览器使用这个配置部署的域名, 不支持跨域

**Comment by padeoe** [comment]
> <img alt="image" width="838" src="https://private-user-images.githubusercontent.com/28623614/291787929-0a469986-e4d6-4c2e-a20b-6de8d0646649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTUzODcsIm5iZiI6MTcwMzA1NTA4NywicGF0aCI6Ii8yODYyMzYxNC8yOTE3ODc5MjktMGE0Njk5ODYtZTRkNi00YzJlLWEyMGItNmRlOGQwNjQ2NjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA2NTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YTZjNWQ3NTcxOGI0ZjE5ZjljZDE3MzE1NTQwY2IzNmUxZDU5NjQ5NTUwNjZhYmJhNzE2ODc3MzlmYjdmZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fryC29rtGZ5G0FgxGODf68kvSZheWqc8cjEhATvZxb8">
> 我用caddy2.7镜像启动, hf-mirror.com.Caddyfile 文件中 109 行 replace 指令识别不了

需要安装 `replace_response` 插件，具体可以在 [官方下载页](https://caddyserver.com/download)勾选这个插件下载打包好的caddy可执行文件或用 `xcaddy`自行编译（参见[这里](https://github.com/caddyserver/replace-response)）。

**Comment by lly-ke** [comment]
<img width="1094" alt="image" src="https://github.com/padeoe/hf-mirror-site/assets/28623614/30a16607-ab9f-430e-a3e9-258687ff1b5a">
在 https://caddyserver.com/download 下载了带 replace_response 模块的二进制文件执行文件, 现在提示replace位置不对 是不是版本太新用不了.

请问你使用的版本是多少

**Comment by padeoe** [comment]
@lly-ke 需要在全局配置里配置
```Caddyfile
{
	order replace after encode
}
```
参见[https://github.com/caddyserver/replace-response?tab=readme-ov-file#caddyfile]，这个我忘了写了，可以试下是不是这个原因

**Comment by lly-ke** [comment]
可以了, 感谢大佬
